name: Docker Image CD

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id:{{secrets.AWS_ACCESS_KEY_ID}} 
        aws-secret-access-key: {{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
    - name: Login to ECR
      run: aws ecr-public get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin public.ecr.aws/g0m7y4h5

    - name: Build,tag and push the Docker image
      run:  |
         docker build .  --tag es-h3/continues-php-image 
         docker tag es-h3/continues_php_image:latest public.ecr.aws/g0m7y4h5/es-h3/continues_php_image:latest^C
         docker push public.ecr.aws/g0m7y4h5/es-h3/continues_php_image:latest
